### ISSUE TITLE
Creator keyword list to moderate comments

### ISSUE THREAD

**Issue by tiger5226** [lbryio/commentron#10]
Offer a keyword list so if someone posts a word in that list, the comment goes to moderation (hidden zone like you said)
For example, if in my list I have the word "crocodile", and someone posts a comment with "crocodile" in it, I can go look and see if they are just talking about crocodiles, or if they are calling me a crocodile. Then i get to delete that and/or block user, or approve the comment.

**Comment by JYamihud** [comment]
Add in UI when writing the comment. A highlight on the word "crocodile" so the person typing the comment will not get confused about what happened to his comment.
