### ISSUE TITLE
Comment Moderation API

### ISSUE THREAD

**Issue by tiger5226** [lbryio/commentron#13]
![Screen Shot 2020-11-12 at 2 12 00 PM](https://user-images.githubusercontent.com/3402064/98985078-0e442f80-24f1-11eb-9f82-cca2fc14797b.png)

**Comment by kauffj** [comment]
also make sure user api returns information so that moderators can be tagged appropriately

**Comment by kauffj** [comment]
potential additional option: block and delete all

**Comment by kauffj** [comment]
Block, block and delete all as first API to add

**Comment by kauffj** [comment]
@tiger5226 any progress on this?

**Comment by tiger5226** [comment]
This is live, needs https://github.com/lbryio/lbry-sdk/issues/3109 for app and @seanyesmunt to implement. The details of the api have been added to https://github.com/lbryio/lbry-desktop/issues/4947

**Comment by tzarebczan** [comment]
needs: 
- also remove and disallow reactions when someone is banned

**Comment by kauffj** [comment]
- unblock
- unhide
