### ISSUE TITLE
Track domain that created a comment

### ISSUE THREAD

**Issue by kauffj** [lbryio/commentron#2]
When a new comment is created, we want to track what domain that comment was made on (e.g. lbry.tv, odysee.com, lbry.lat, etc).

**Comment by tiger5226** [comment]
this requires adding a column to the comment table, getting the domain from the request and storing it.

**Comment by tiger5226** [comment]
Add a var char column of length 50 ( all domains we use should be able to fit in there ) that can be null, so it doesn't cause a large migration on the db and old records can remain unimpacted.

**Comment by tiger5226** [comment]
only one domain now
