### ISSUE TITLE
Moderation Delegation

### ISSUE THREAD

**Issue by tiger5226** [lbryio/commentron#20]
Allow an API for creators to assign channels as moderators, who have permissions to block users from commenting.

**Comment by tiger5226** [comment]
moderation.SetModerator
moderation.ListModerators
moderation.RemoveModerator

**Comment by tzarebczan** [comment]
Is this fully completed? I know some parts were.

**Comment by tiger5226** [comment]
`moderation.AmI` - Checks if a user is a moderator for a specific channel
`moderation.Block` - Blocks channels but now allows delegated moderators to block
`moderation.UnBlock` - UnBlocks channels that were blocked
`moderation.ListDelegates` - List delegated moderators
`moderation.AddDelegate` - Add delegated moderator
`moderation.RemoveDelegate` - Remove delegated moderator

This is completed, and waiting to hear from @infinite-persistence to see if there are any changes required. He mentioned an issue with `moderation.ListDelegates` which I will push a fix for.
