### ISSUE TITLE
Please don't censor people. Banning words isn't helpful.

### ISSUE THREAD

**Issue by robd003** [lbryio/commentron#29]
I'd much rather have the community upvote / downvote comments than have a channel decide that there's a list of "naughty words" that can't be said.

The best disinfectant is sunlight.

**Comment by kauffj** [comment]
Hi @robd003, we agree with you. This list is a temporary solution to please some of the larger streamers. It will become a streamer controlled option and list in the near future. We do think it should be each creator's option to decide what kind of commentary they want to allow.
