### ISSUE TITLE
channel names with special chars (app crash)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/commentron#5]
This file has a comment that isn’t being returned properly. https://odysee.com/@TheQuartering:1/instant-regret-youtube-mocks-creators:e
This channel created a comment https://lbry.tv/@%F0%9F%8C%80Epic%E2%97%84%E2%96%BAGames%E2%9C%94:d
The comment server is returning the authorURI as “lbry://@?Epic...” instead of “lbry://@:cyclone:EpicGames”  replacing the emoji with a question mark. It’s causing the page to crash because a question mark makes it an invalid URI. Can this be fixed on the comment server? (edited) 

Claim id: 

d89c5f31b688dc8097714dc0cb1694a5707067e2

**Comment by tiger5226** [comment]
@akinwale I am using character set `utf8mb4_unicode_ci` for the name column which is exactly what I am using in Chainquery. Thats the right one to capture this encoding right? 

@tzarebczan Its either the jsonrpc protocol or its what I was passed from the API if @akinwale confirms.

**Comment by akinwale** [comment]
@tiger5226 Yes, that's the correct encoding. Maybe it's been re-encoded or escaped incorrectly somewhere along the way? The only way to confirm for sure would be to check the actual data stored in the database.

**Comment by tzarebczan** [comment]
This data was fixed in commentron. Some old notifications may still crash stuff.
