### ISSUE TITLE
Add yourself as moderator - Bug?

### ISSUE THREAD

**Issue by GlobalGamer2015** [lbryio/commentron#52]
I'm not sure if your meant to do this but you can add yourself as a moderator on your own channel.
![Screenshot_638](https://user-images.githubusercontent.com/19220996/125500791-2a0606ed-67ec-49ed-ac18-03a3ced3bc13.jpg)

**Comment by tzarebczan** [comment]
Yes, this is possible today but we should probably prevent it from the UI side. Doesn't really change much in the backend or how moderation works.

**Comment by tiger5226** [comment]
This is being deployed now.
